{"name": "test_auth_invalid_data", "status": "passed", "description": "\n        Steps\n        1. Open main page\n        2. Auth with invalid data\n        3. Check auth result.\n        ", "attachments": [{"name": "log", "source": "08cf66fd-e5e5-4ee9-aa3e-ef0835733cdd-attachment.txt", "type": "text/plain"}], "start": 1632931870387, "stop": 1632931872778, "uuid": "33f0e293-b704-49c9-b649-afdc11117021", "historyId": "695f55378f8fe30fa2f217e0f6c38726", "testCaseId": "3288b5f502ddd6e63bc2e3b025925971", "fullName": "tests.auth.test_auth.TestAuth#test_auth_invalid_data", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "DESKTOP-1VT1IRI"}, {"name": "thread", "value": "6336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_auth"}]}