{"name": "test_auth_invalid_data", "status": "passed", "description": "\n        Steps\n        1. Open main page\n        2. Auth with no valid data\n        3. Check auth result.\n        ", "attachments": [{"name": "log", "source": "37dad086-451d-4a2d-8b9b-5ffae4456a6c-attachment.txt", "type": "text/plain"}], "start": 1632772855411, "stop": 1632772856976, "uuid": "bed01057-f846-40f9-b418-e784ce601fb1", "historyId": "695f55378f8fe30fa2f217e0f6c38726", "testCaseId": "3288b5f502ddd6e63bc2e3b025925971", "fullName": "tests.auth.test_auth.TestAuth#test_auth_invalid_data", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "DESKTOP-1VT1IRI"}, {"name": "thread", "value": "7912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_auth"}]}